# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'erp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for erp
  pod 'Alamofire'
  pod 'SDWebImage'
    
  target 'erpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'erpUITests' do
    # Pods for testing
  end

end
